mode: eval
seed: 42
paths:
  project_root: /home/hmq/zyq/PatchTST
  output_root: /home/hmq/zyq/PatchTST/outputs
  test_csv:
  val_csv:
  model_path:
  norm_stats_path:
runtime:
  device: auto
  npu_device_index: 0
  cuda_device_index: 0
data:
  timestamp_col: timestamp
  timestamp_format: '%Y-%m-%d %H:%M:%S'
  feature_columns:
  - irr_ghi
  feature_columns_csv: B(ghi_kt|5min),B(ghi_kt|10min),B(ghi_kt|15min),B(ghi_kt|20min),B(ghi_kt|25min),B(ghi_kt|30min),B(dni_kt|5min),B(dni_kt|10min),B(dni_kt|15min),B(dni_kt|20min),B(dni_kt|25min),B(dni_kt|30min),V(ghi_kt|5min),V(ghi_kt|10min),V(ghi_kt|15min),V(ghi_kt|20min),V(ghi_kt|25min),V(ghi_kt|30min),V(dni_kt|5min),V(dni_kt|10min),V(dni_kt|15min),V(dni_kt|20min),V(dni_kt|25min),V(dni_kt|30min),L(ghi_kt|5min),L(ghi_kt|10min),L(ghi_kt|15min),L(ghi_kt|20min),L(ghi_kt|25min),L(ghi_kt|30min),L(dni_kt|5min),L(dni_kt|10min),L(dni_kt|15min),L(dni_kt|20min),L(dni_kt|25min),L(dni_kt|30min),irr_ghi,irr_dni,irr_dhi
  target_column: target_ghi_15min
  sequence_length: 120
  target_horizon_minutes: 15
  time_interval_minutes: 5
  time_gap_policy: warn
model:
  hidden_size: 128
  depth: 3
  dim_head: 32
  heads: 4
  ff_mult: 4
  dropout: 0.1
  num_mem_tokens: 4
  use_reversible_instance_norm: true
  reversible_instance_norm_affine: true
  flash_attn: true
eval:
  batch_size: 256
  num_workers: 0
  plot_points: 300
  result_csv_file: test_predictions.csv
  ws_alpha: 0.1
